### ISSUE TITLE
Chapter 3 - Docker modules citation doesn't resolve

### ISSUE THREAD

**Issue by js-mode** [geerlingguy/ansible-for-kubernetes#54] opened 2020-05-28 22:19 UTC
Page 42: [Docker modules<sup>40</sup>](https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html%23docker)

Returns 404 page not found error. -- looks like it is an encoding issue. Should resolve to: https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#docker

**Comment by geerlingguy** [comment] 2020-06-07 02:32
@js-mode - Thanks for finding this. The Ansible docs are kind of going all over the place for the past couple months as the project is rearranged. I'll try to get all my other docs links fixed as well!

**Comment by geerlingguy** [comment] 2020-09-01 03:57
@js-mode - This is interesting... I can confirm the same behavior when viewing the PDF on my computer.

I filed an upstream issue in the LeanPub Authors forum: https://community.leanpub.com/t/footnote-links-with-anchors-get-encoded-to-23-dont-work/2457 (you might have to be a LeanPub user for that link to work). Hopefully there will be some answer so I can fix this bug.

**Comment by geerlingguy** [comment] 2020-09-01 15:59
According to a commenter on the leanpub post above:

> this seems to be a bug in the macOS Preview.app

And testing the same PDF in Adobe Acrobat, I can confirm that the issue does _not_ exist there. It seems to be a bug in the latest version of Preview on macOS, so hopefully Apple gets it fixed soon!

Here's what the link looks like on hover in Acrobat:

<img width="624" alt="Screen Shot 2020-09-01 at 10 56 59 AM" src="https://user-images.githubusercontent.com/481677/91876270-202c6b00-ec42-11ea-815a-386a32b59d37.png">

And if I click on it, it takes me to the right page and anchor link, no problem.

Since this is something out of my hands (and out of LeanPub's, since the PDF is generated correctly), I'm going to close the issue.

**Closed by geerlingguy** 2020-09-01 15:59 UTC
